# _config.yml — minimal Jekyll configuration
title: Brainiacs
baseurl: "/Brainiacs"          # the repo name, keep the leading slash
permalink: /:path/             # default → /filename/  (drops “.html”)
